// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxYS6nji3sT1I0e2d-P7bkoZngkC7cR8',
    appId: '1:1041637534448:web:8c663783add2ac35663035',
    messagingSenderId: '1041637534448',
    projectId: 'eyecareapp-f51a4',
    authDomain: 'eyecareapp-f51a4.firebaseapp.com',
    storageBucket: 'eyecareapp-f51a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvqmGiOz2JfgkDFwbH8z1ZBLSEtm1TaKE',
    appId: '1:1041637534448:android:42770e0345304033663035',
    messagingSenderId: '1041637534448',
    projectId: 'eyecareapp-f51a4',
    storageBucket: 'eyecareapp-f51a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlhih8hUArJCzqDud7tuP4uFRxLtsGFwA',
    appId: '1:1041637534448:ios:c2141ca355bb0a5b663035',
    messagingSenderId: '1041637534448',
    projectId: 'eyecareapp-f51a4',
    storageBucket: 'eyecareapp-f51a4.appspot.com',
    iosClientId: '1041637534448-ot7fhemhu7t5uh3bh444lahh1npbc2kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlhih8hUArJCzqDud7tuP4uFRxLtsGFwA',
    appId: '1:1041637534448:ios:c2141ca355bb0a5b663035',
    messagingSenderId: '1041637534448',
    projectId: 'eyecareapp-f51a4',
    storageBucket: 'eyecareapp-f51a4.appspot.com',
    iosClientId: '1041637534448-ot7fhemhu7t5uh3bh444lahh1npbc2kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcareApp',
  );
}
